spring.application.name=bibliotecabd

# 1. Configuración de la URL de conexión JDBC
# Formato: jdbc:oracle:thin:@localhost:PUERTO:SID o SERVICE_NAME
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe

# 2. Credenciales del usuario Administrador
spring.datasource.username=ADMINISTRADOR
spring.datasource.password=mibd1

# 3. Driver de Oracle
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# 4. Configuración de JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
# 'update' crea o modifica automáticamente las tablas según tus clases @Entity
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true